//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class incomeDetail
    {
        public long appId { get; set; }
        public string propLoc { get; set; }
        public string propName { get; set; }
        public int propAmount { get; set; }
        public byte[] empType { get; set; }
        public int retirementAge { get; set; }
        public string orgType { get; set; }
        public string employer { get; set; }
    
        public virtual application application { get; set; }
    }
}
