//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public long loanId { get; set; }
        public string status { get; set; }
        public int amountApproved { get; set; }
        public int noOfEmiTotal { get; set; }
        public int noOfEmiLeft { get; set; }
        public System.DateTime loanDateStart { get; set; }
        public string remarks { get; set; }
        public long adminId { get; set; }
    
        public virtual application application { get; set; }
        public virtual login login { get; set; }
    }
}
