//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalDetail
    {
        public long appId { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public long phoneNumber { get; set; }
        public System.DateTime DOB { get; set; }
        public string gender { get; set; }
        public byte[] nationality { get; set; }
    
        public virtual application application { get; set; }
    }
}
