//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userBankDetail
    {
        public long appId { get; set; }
        public long accNo { get; set; }
        public string ifsc { get; set; }
    
        public virtual application application { get; set; }
    }
}
